### ISSUE TITLE
Reward Doubler Panes

### ISSUE THREAD

**Issue by ParadiseNICK** [Quantum64/ArcadeAPI#1]
&c&l&nClaim Current Reward
&7
&7Claim the reward you just opened up!
&7Doing this will only give you &c1x&7 your
&7original reward. That's no fun, is it?
the star:
&6&lWhat is this?

&7You just opened a crate and now
&7have a chance to either &adouble
&7your reward, or keep the &coriginal&7.
&7This requires &a&lG-Tokens&7 which can
&7be earned by watching &c&l&n/ads&7.

&a&l&nClick To Double
on the green and blue pane
that's good

**Comment by Quantum64** [comment]
Done
