### ISSUE TITLE
Skyblock /is top GUI

### ISSUE THREAD

**Issue by silverex** [Quantum64/ArcadeAPI#16]
Type /is top, GUI pops up with the top 20 islands based on island level, represented by the skull of the island owner. Hovering over each head shows various info about the island. Example:
[Item name] Island of <username> (<position>)
[Lore]
Place: # 1 
Island Level: xxxx
Members:
    bob
    joe
    barbara
Island Worth: $money (maybe, I'm not sure how it's calculated on pvpwars.net but probably hooks into a shop + player balance?)
https://gyazo.com/3191d5db2bc4bd7cc4834e1c881ea031

Left click on the head to show block information about the island (blocks of the highest level and how many of them are on the island). Spawners are separated by type. Title of the GUI has player name and worth (if you can't do worth, do island level)
 https://gyazo.com/4167ae811c34f150f559aaef11eec63a
Right click to teleport to their island warp (/is warp <username>). If they don't have one, display a message in chat stating the user doesn't have a warp.

Things that should be configurable:
Amount of islands shown in the GUI
Amount of blocks shown in the top blocks category

**Comment by Quantum64** [comment]
How exactly is this arcade related?
