### ISSUE TITLE
Global /staff Command

### ISSUE THREAD

**Issue by silverex** [Quantum64/ArcadeAPI#17]
Typing /staff shows a list of which staff are currently online. Hovering over their usernames shows what server they are currently on.
https://gyazo.com/d05c942afd7f563060167fd9f71cec32
Don't show the ranks that have no staff online. 
Ranks should be formatted the same as the pex prefixes.

**Comment by Quantum64** [comment]
This is probably not possible due to the way arcade handles player data

**Comment by Quantum64** [comment]
Good thing it's not handled the same way anymore... done
