### ISSUE TITLE
Ads Leaderboard

### ISSUE THREAD

**Issue by ParadiseNICK** [Quantum64/ArcadeAPI#2]
- Leaderboard placeholders for GTOKEN SHOP
     - Automatically give the leaders extra G-Tokens and tell them in game they won (resets weekly, stored in MySQL)
     - 1st place: 100 G-Tokens     ----------- first place will be announced when the gtokens are given

"&f&l(&e&lPMC&f&l) &c&l** &aLeaderboard Update &c&l** &d&n{name} &awatched the most ads last week and was rewarded with &d&l7n100 G-Tokens&f. &aWatch ads to be the new leader next week through &d&l&n/ads&a.

     - 2nd place: 75 G-Tokens
     - 3rd place: 50 g-tokens
     - 4th place: 40
     - 5th place: 30
     - 6th place: 20
     - 7th place: 15
     - 8th-10th place: 10

**Comment by Quantum64** [comment]
Done
