### ISSUE TITLE
Weekly Leaderboard

### ISSUE THREAD

**Issue by ParadiseNICK** [Quantum64/ArcadeAPI#21]
Would be nice if this could reset every week.

Maybe a placeholder for it %time% places this under the "Leaderboard" title

&7Top 10 per week get extra tokens!
&7Only 00:00:00 left until board reset!

**Comment by Quantum64** [comment]
Probably won't happen and if it does this will take a really long time to implement.

**Comment by Quantum64** [comment]
Replaced by #22
