### ISSUE TITLE
Staff join messages

### ISSUE THREAD

**Issue by Kailied** [Quantum64/ArcadeAPI#25]
I, KailNub, and many other staff find it difficult to catch some hackers or rule breakers, as a lot of us have a join message from our Immortal+ rank.
Taking away these join messages for (in my opinion) Mod+, maybe even T.Mod+ would really help us out, but for certain gamemodes where hacking is common such as KitPVP, others being Factions, Skywars and Trenches.
I've heard a lot of staff saying this has been a requested feature for a long time, and I think it's about time that it be added, as to assist staff in better doing their job.

**Comment by Quantum64** [comment]
@ParadiseNICK comment

**Comment by silverex** [comment]
If this is approved, the displaying of those messages should be toggleable.

**Comment by Quantum64** [comment]
Done
